language: java
jdk:
  - oraclejdk8
script: ant build
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "<.... encryption label from previous step ....>"
  - COMMIT_AUTHOR_EMAIL: "elubecka@inf.ug.edu.pl"
