language: java
jdk:
  - oraclejdk8
script: ant build
script: bash ./push.sh
deploy:
  skip_cleanup: true
env:
  global:
  - ENCRYPTION_LABEL: "<.... encryption label from previous step ....>"
  - COMMIT_AUTHOR_EMAIL: "elubecka@inf.ug.edu.pl"
